### ISSUE TITLE
Remove the default 'Notebook' title if there is no title in the metadata

### ISSUE THREAD

**Issue by johnhekman** [m-rossi/jupyter-docx-bundler#28]
Hi, I was wondering why the output of this gives me a 'Notebook' title when the notebook metadata has no title. Is this intentional default behaviour?

**Comment by m-rossi** [comment]
When I implemented it, there was an issue upstream in `nbconvert` regarding title. This is fixed for some time now. The default behaviour of `nbconvert` is to put _Notebook_ there.
However, I haven‘t checked the output without a title since then, because I always use a title. I can put some code in to remove the title completely if there is none.

**Comment by m-rossi** [comment]
@johnhekman the code to prevent this behavior is in the master branch now. Feel free to use the development version or wait for the release of the next version. Thanks for your your recommendation!
